version: '3.8'

services:
  # Development frontend
  citizen-portal:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api/v1
    networks:
      - civicstream-network

networks:
  civicstream-network:
    external: true